### ISSUE TITLE
Having an issue correctly parsing the mta feed

### ISSUE THREAD

**Issue by merryprankster02** [edwarddistel/mta-subway-countdown-clock#1]
i cant seem to have this prodouce any results. It locates the station correctly but doesnt return any times. Below is the error that i see:

{"stations":{"L20N":{"name":"Wilson Av","trains":[]},"L20S":{"name":"Wilson Av","trains":[]}},"status":"error","message":"Error. Something went wrong with parsing the MTA feed. Error: invalid wire type 6 at offset 10"}

**Comment by sconnick** [comment]
I'm getting the same error message(s) when I execute the program as well.  Did you have any success getting it up and running?

**Comment by edwarddistel** [comment]
Sorry I just saw this. The MTA completely redid their APIs and I was too busy to notice -- I made some changes, should be working now.
